#!/bin/bash

echo Removing...

rm -r /Library/LaunchDaemons/com.dpkg.EXVSD.Daemon.plist

cd /System/Library/LaunchDaemons
echo "<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnablePressuredExit</key>
	<true/>
	<key>EnableTransactions</key>
	<true/>
	<key>Label</key>
	<string>com.apple.videosubscriptionsd</string>
	<key>LaunchEvents</key>
	<dict>
		<key>com.apple.distnoted.matching</key>
		<dict>
			<key>Application Installed</key>
			<dict>
				<key>Name</key>
				<string>com.apple.LaunchServices.applicationRegistered</string>
			</dict>
			<key>Application Uninstalled</key>
			<dict>
				<key>Name</key>
				<string>com.apple.LaunchServices.applicationUnregistered</string>
			</dict>
		</dict>
	</dict>
	<key>MachServices</key>
	<dict>
		<key>com.apple.VideoSubscriberAccount.videosubscriptionsd</key>
		<true/>
	</dict>
	<key>POSIXSpawnType</key>
	<string>Adaptive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/libexec/videosubscriptionsd</string>
	</array>
	<key>UserName</key>
	<string>mobile</string>
</dict>
</plist>" > /System/Library/LaunchDaemons/com.apple.videosubscriptionsd.plist && chmod 644 /System/Library/LaunchDaemons/com.apple.videosubscriptionsd.plist

echo REMOVED SUCCESSFULLY.

exit 0